server:
  port: 1608
eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      register-with-eureka: true
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
        - id: MOVIE-BOOKING-SERVICE
          uri: lb://MOVIE-BOOKING-SERVICE
          predicates:
            - Path=/movie-booking/**
        - id: MOVIE-SERVICE
          uri: lb://MOVIE-SERVICE
          predicates:
            - Path=/movie/**
        - id: PAYMENT-SERVICE
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment/**
        - id: THEATRE-SERVICE
          uri: lb://THEATRE-SERVICE
          predicates:
            - Path=/theatre/**